force-app/main/default/objects/Loan_Charge__c/Loan_Charge__c.object-meta.xml
<CustomObject>
    <description>This object records various charges associated with each loan</description>
    <label>Loan Charge</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Loan Charge Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Charge__c/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <label>Charge Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Interest Charge</fullName>
            </value>
            <value>
                <fullName>Legal Fee</fullName>
            </value>
            <value>
                <fullName>Release Charge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Charge__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>The date the charge was applied.</description>
    <label>Charge Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/LoanChargeSort.cls
public without sharing class LoanChargeSort implements Comparator<Loan_Charge__c> {
    public Integer compare(Object a, Object b) {
        Loan_Charge__c c1 = (Loan_Charge__c)a;
        Loan_Charge__c c2 = (Loan_Charge__c)b;

        // First sort by Date__c
        if (c1.Date__c != null && c2.Date__c != null && c1.Date__c != c2.Date__c) {
            return c1.Date__c < c2.Date__c ? -1 : 1;
        }

        // Compare priority
        Integer p1 = getPriority(c1.Charge_Type__c);
        Integer p2 = getPriority(c2.Charge_Type__c);

        if (p1 < p2) {
          return -1;
        }
        if (p1 > p2) {
          return 1;
        }
        return 0;
    }

    public Integer getPriority(String type) {
        if (type == 'Admin Fee') {
          return 0;
        } else if (type == 'Interest Charge') {
          return 1;
        }

        return 2;
    }
}