force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Person Accounts only</errorMessage>
        <filterItems>
            <field>Account.PersonContact.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Date_Loan_Issued__c.field-meta.xml
<CustomField>
    <fullName>Date_Loan_Issued__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>The date the loan was initially issued.</description>
    <label>Loan Issue Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Gross_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Gross_Loan_Amount__c</fullName>
    <description>The initial total amount of the loan issued</description>
    <label>Gross Loan Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <description>The duration of the loan in months.</description>
    <label>Loan Term (Months)</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Charge__c/Loan_Charge__c.object-meta.xml
<CustomObject>
    <description>This object records various charges associated with each loan</description>
    <label>Loan Charge</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Loan Charge Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Charge__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The monetary value of the charge.</description>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Charge__c/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <label>Charge Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Interest Charge</fullName>
            </value>
            <value>
                <fullName>Legal Fee</fullName>
            </value>
            <value>
                <fullName>Release Charge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Charge__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>The date the charge was applied.</description>
    <label>Charge Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan_Charge__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>A master-detail or lookup relationship to the Loan__c object, associating the charge with its respective loan.</description>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Loans Charge</relationshipLabel>
    <relationshipName>Loans_Charge</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Validation_Bypass__c/Validation_Bypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Test if it&apos;s test suit</description>
    <label>Validation Bypass</label>
</CustomObject>

force-app/main/default/objects/Validation_Bypass__c/fields/Bypass_Validation__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Remove the validation</description>
    <label>Bypass Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LoanTriggerHandler_Test.cls
@isTest
private class LoanTriggerHandler_Test {

  @testSetup
  static void setupBypassAndAccount() {
    // Bypass validation during test
    Validation_Bypass__c bypass = new Validation_Bypass__c(
        SetupOwnerId = UserInfo.getUserId(),
        Bypass_Validation__c = true
    );
    insert bypass;
  }

  @isTest
  /**
   * @description Test onAfterInsert()
   */
  static void testOnAfterInsertCreatesReleaseCharge() {
      Account acct = new Account(
          FirstName = 'Automated',
          LastName = 'Test User',
          RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId()
      );

      insert acct;

      // Insert loan
      Loan__c loan = new Loan__c(
          Name = 'Loan Insert Test',
          Account__c = acct.Id,
          Date_Loan_Issued__c = Date.today(),
          Term__c = 12,
          Gross_Loan_Amount__c = 10000
      );

      Test.startTest();
      insert loan;
      Test.stopTest();

      List<Loan_Charge__c> charges = [
          SELECT Id, Loan__c, Charge_Type__c, Amount__c, Date__c
          FROM Loan_Charge__c
          WHERE Loan__c = :loan.Id
      ];

      System.assertEquals(1, charges.size(), 'Should create one Release Charge');
      System.assertEquals('Release Charge', charges[0].Charge_Type__c, 'Expected a Release Charge to be created');
      System.assertEquals(500, charges[0].Amount__c, 'Expected Release Charge amount to be £500');
  }

  @isTest
  /**
   * @description Test onAfterUpdate()
   */
  static void testOnAfterUpdateCreatesAdminFeeUpdatesReleaseCharge() {
      Account acct = new Account(
          FirstName = 'Automated',
          LastName = 'Test User',
          RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId()
      );

      insert acct;

      // Insert loan
      Loan__c loan = new Loan__c(
          Name = 'Loan Update Test',
          Account__c = acct.Id,
          Date_Loan_Issued__c = Date.today(),
          Term__c = 12,
          Gross_Loan_Amount__c = 10000
      );
      insert loan;

      // Get Release Charge
      Loan_Charge__c releaseBefore = [
          SELECT Id, Date__c
          FROM Loan_Charge__c
          WHERE Loan__c = :loan.Id AND Charge_Type__c = 'Release Charge'
          LIMIT 1
      ];
      Date oldDate = releaseBefore.Date__c;

      // Update term
      loan.Term__c = 18;

      Test.startTest();
      update loan;
      Test.stopTest();

      // Assert admin fee added
      List<Loan_Charge__c> adminFees = [
          SELECT Id
          FROM Loan_Charge__c
          WHERE Loan__c = :loan.Id AND Charge_Type__c = 'Admin Fee'
      ];
      System.assertEquals(1, adminFees.size(), 'Should create one Admin Fee charge');

      // Assert release charge date updated
      Loan_Charge__c releaseAfter = [
          SELECT Id, Date__c
          FROM Loan_Charge__c
          WHERE Id = :releaseBefore.Id
      ];
      System.assert(releaseAfter.Date__c > oldDate, 'Release Charge date should be updated');
  }
}